apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvkodbdi-backend-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvkodbdi-backend
  template:
    metadata:
      labels:
        app: tvkodbdi-backend
    spec:
      containers:
        - name: tvkodbdi-backend
          image: tvkodbdi-backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: backend-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: tvkodbdi-backend-service
spec:
  selector:
    app: tvkodbdi-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

