apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvkodbdi-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvkodbdi-frontend
  template:
    metadata:
      labels:
        app: tvkodbdi-frontend
    spec:
      containers:
        - name: tvkodbdi-frontend
          image: ${REGISTRY}/${IMAGE_REPO}/frontend:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tvkodbdi-frontend-service
spec:
  selector:
    app: tvkodbdi-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080
  type: NodePort
